### ISSUE TITLE
Interaction

### ISSUE THREAD

**Issue by asolove** [gigamonkey/gg#10]
I would like to think about how to extend the underlying grammar to include support for various forms of interaction. 

Some sample interactions:

- Clicking on an interval representing a group of data to see the subdivision of smaller data points.
- Highlighting related data points when hovering on one of them.
- Zooming in or out on specific regions of large, data-rich graphs. 
- Hiding/displaying individual sets of data.

The basic goal is to make computerized graphics take full advantage of the screen medium and allow viewers to perform analytical work not necessarily envisioned by the designer of the original graphic.

I know a number of people are currently working in this area. I plan to post research notes to this issue as I find interesting things to read.

**Comment by LukasGrebe** [comment]
A filter Interaction is nicely realized by http://square.github.io/crossfilter/
